packages:
  - packages/*
  - services/backend/*
  - services/frontend/*
  - scripting

overrides:
  create-express-app: link:C:/Users/LENOVO/AppData/Local/pnpm/global/5/node_modules/@mrknown404/create-express-app
