export const DEPARTMENTS = [
  { acronym: "AI&DS", name: "Artificial Intelligence & Data Science" },
  { acronym: "AIML", name: "Artificial Intelligence & Machine Learning" },
  { acronym: "Biotech", name: "Biotechnology" },
  { acronym: "CH", name: "Chemical Engineering" },
  { acronym: "Civil", name: "Civil Engineering" },
  { acronym: "CSE", name: "Computer Science & Engineering" },
  { acronym: "CSE(AIML)", name: "Computer Science & Engineering (AI & ML)" },
  { acronym: "CSE(CY)", name: "Computer Science & Engineering (Cyber Security)" },
  { acronym: "ECE", name: "Electronics & Communication Engineering" },
  { acronym: "EIE", name: "Electronics & Instrumentation Engineering" },
  { acronym: "EEE", name: "Electrical & Electronics Engineering" },
  { acronym: "ETE", name: "Electronics & Telecommunication Engineering" },
  { acronym: "IEM", name: "Industrial Engineering & Management" },
  { acronym: "ISE", name: "Information Science & Engineering" },
  { acronym: "Mechanical", name: "Mechanical Engineering" },
  { acronym: "MD", name: "Medical Electronics Engineering" },
  { acronym: "MCA", name: "Master of Computer Applications" },
  { acronym: "MBA", name: "Management Studies (MBA)" },
  { acronym: "Aerospace", name: "Aerospace Engineering" },
  { acronym: "Arch", name: "Architecture" },
];
