export const DEPARTMENTS = [
  { value: "AI&DS", label: "Artificial Intelligence & Data Science" },
  { value: "AIML", label: "Artificial Intelligence & Machine Learning" },
  { value: "Biotech", label: "Biotechnology" },
  { value: "CH", label: "Chemical Engineering" },
  { value: "Civil", label: "Civil Engineering" },
  { value: "CSE", label: "Computer Science & Engineering" },
  { value: "CSE(AIML)", label: "Computer Science & Engineering (AI & ML)" },
  {
    value: "CSE(CY)",
    label: "Computer Science & Engineering (Cyber Security)",
  },
  { value: "ECE", label: "Electronics & Communication Engineering" },
  { value: "EIE", label: "Electronics & Instrumentation Engineering" },
  { value: "EEE", label: "Electrical & Electronics Engineering" },
  { value: "ETE", label: "Electronics & Telecommunication Engineering" },
  { value: "IEM", label: "Industrial Engineering & Management" },
  { value: "ISE", label: "Information Science & Engineering" },
  { value: "Mechanical", label: "Mechanical Engineering" },
  { value: "MD", label: "Medical Electronics Engineering" },
  { value: "MCA", label: "Master of Computer Applications" },
  { value: "MBA", label: "Management Studies (MBA)" },
  { value: "M.Tech", label: "Master of Technology" },
  { value: "Aerospace", label: "Aerospace Engineering" },
  { value: "Arch", label: "Architecture" },
];
