import {
  Globe,
  Brain,
  Terminal,
  ShieldAlert,
  FileText,
  Cpu,
  Smartphone,
  Gamepad2,
  Wrench,
  Lightbulb,
  type LucideIcon,
} from "lucide-react";
import { Chapters as CatalogChapters, OrganizationStructure } from "@astranova/catalogues";

export const EDIT_PROJECT_TYPE_META: Record<
  string,
  { Icon: LucideIcon; iconColor: string; borderColor: string; bgColor: string }
> = {
  website: {
    Icon: Globe,
    iconColor: "#00cfff",
    borderColor: "rgba(0,207,255,0.3)",
    bgColor: "rgba(0,207,255,0.06)",
  },
  aiml: {
    Icon: Brain,
    iconColor: "#ff4fd8",
    borderColor: "rgba(255,79,216,0.3)",
    bgColor: "rgba(255,79,216,0.06)",
  },
  cli: {
    Icon: Terminal,
    iconColor: "#00ff9d",
    borderColor: "rgba(0,255,157,0.25)",
    bgColor: "rgba(0,255,157,0.05)",
  },
  cybersecurity: {
    Icon: ShieldAlert,
    iconColor: "#ffb700",
    borderColor: "rgba(255,183,0,0.3)",
    bgColor: "rgba(255,183,0,0.06)",
  },
  research: {
    Icon: FileText,
    iconColor: "rgba(200,255,232,0.6)",
    borderColor: "rgba(200,255,232,0.15)",
    bgColor: "rgba(200,255,232,0.04)",
  },
  embedded: {
    Icon: Cpu,
    iconColor: "#ff4fd8",
    borderColor: "rgba(255,79,216,0.25)",
    bgColor: "rgba(255,79,216,0.05)",
  },
  mobile: {
    Icon: Smartphone,
    iconColor: "#00cfff",
    borderColor: "rgba(0,207,255,0.25)",
    bgColor: "rgba(0,207,255,0.05)",
  },
  game: {
    Icon: Gamepad2,
    iconColor: "#ffb700",
    borderColor: "rgba(255,183,0,0.25)",
    bgColor: "rgba(255,183,0,0.05)",
  },
  devtool: {
    Icon: Wrench,
    iconColor: "#00ff9d",
    borderColor: "rgba(0,255,157,0.22)",
    bgColor: "rgba(0,255,157,0.05)",
  },
  other: {
    Icon: Lightbulb,
    iconColor: "rgba(200,255,232,0.5)",
    borderColor: "rgba(200,255,232,0.12)",
    bgColor: "rgba(200,255,232,0.03)",
  },
};

export const PROJECT_TYPES = [
  { value: "website", label: "Website / Web App" },
  { value: "aiml", label: "AI / ML Project" },
  { value: "cli", label: "CLI / Tooling" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "research", label: "Research Paper" },
  { value: "embedded", label: "Embedded / Hardware" },
  { value: "mobile", label: "Mobile App" },
  { value: "game", label: "Game" },
  { value: "devtool", label: "Dev Tool / Library" },
  { value: "other", label: "Other" },
] as const;

export const PROJECT_TAGS = [
  "web",
  "ai",
  "ml",
  "cli",
  "security",
  "hardware",
  "embedded",
  "mobile",
  "game",
  "research",
  "open-source",
  "backend",
  "frontend",
  "fullstack",
  "api",
  "database",
  "devops",
  "cloud",
  "python",
  "typescript",
  "rust",
  "go",
  "c++",
  "react",
  "next.js",
  "node.js",
  "competition",
  "ieee",
  "hackathon",
  "robotics",
  "iot",
  "blockchain",
  "networking",
];

export const AVAILABLE_SKILLS = [
  "Arduino",
  "Raspberry Pi",
  "ESP32",
  "Verilog",
  "VHDL",
  "Embedded C",
  "FPGA",
  "ARM Cortex",
  "PCB Design",
  "RTOS",
  "I2C/SPI/UART",
  "Firmware Development",
  "Microcontrollers",
  "C",
  "C++",
  "C#",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Rust",
  "Go",
  "Kotlin",
  "Swift",
  "SQL",
  "Bash",
  "PHP",
  "HTML5/CSS3",
  "React",
  "Next.js",
  "Vue.js",
  "TailwindCSS",
  "Svelte",
  "Angular",
  "Flutter",
  "React Native",
  "Three.js",
  "Node.js",
  "Express",
  "FastAPI",
  "Django",
  "Spring Boot",
  "GraphQL",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "SQLite",
  "Redis",
  "Elasticsearch",
  "Linux/Unix",
  "Git",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud (GCP)",
  "Azure",
  "CI/CD (GitHub Actions)",
  "Terraform",
  "Nginx",
  "PyTorch",
  "TensorFlow",
  "OpenCV",
  "ROS (Robot Operating System)",
  "Numpy",
  "Pandas",
  "Scikit-Learn",
  "Machine Learning",
  "Deep Learning",
  "Computer Vision",
  "NLP",
  "Penetration Testing",
  "Cryptography",
  "Network Security",
  "Reverse Engineering",
  "Linux Kernel",
  "Web Security",
];

export const CHAPTER_OPTIONS: { value: string; label: string }[] = [
  ...OrganizationStructure.map((c) => ({ value: c.acronym, label: c.name }))
];
